# Docker compose for netflix conductor + elasticsearch + dynomite
version: '2'
services:
  conductor-server:
    environment:
      - CONFIG_PROP=config.properties
    image: vmunnangi/conductor-mine:01
    ports:
      - 8080:8080
    links:
      - elasticsearch:es
      - dynomite:dyno1

  conductor-ui:
    environment:
      - WF_SERVER=http://conductor-server:8080/api/
    image: vmunnangi/conductor-mine-ui:01
    ports:
      - 5000:5000
    links:
      - conductor-server



  elasticsearch:
    image: elasticsearch:2.4
